# Generated by Django 4.1 on 2022-09-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='department',
            field=models.CharField(blank=True, max_length=200, verbose_name='Подразделение'),
        ),
        migrations.AddField(
            model_name='group',
            name='faculty',
            field=models.CharField(blank=True, max_length=200, verbose_name='Факультет'),
        ),
        migrations.AddField(
            model_name='group',
            name='level',
            field=models.CharField(blank=True, max_length=200, verbose_name='Уровень'),
        ),
        migrations.AddField(
            model_name='group',
            name='number_of_active_students',
            field=models.CharField(blank=True, max_length=2, verbose_name='Количество студентов'),
        ),
        migrations.AddField(
            model_name='group',
            name='study_form',
            field=models.CharField(blank=True, max_length=200, verbose_name='Форма обучения'),
        ),
        migrations.AddField(
            model_name='group',
            name='term_number',
            field=models.CharField(blank=True, max_length=2, verbose_name='Период'),
        ),
    ]
