# Generated by Django 4.1 on 2022-09-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_group_department_group_faculty_group_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff',
            name='type',
            field=models.IntegerField(default=1, max_length=1, verbose_name='Должность'),
        ),
    ]
