# Generated by Django 4.1 on 2022-09-18 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_stuff_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stuff',
            name='type',
        ),
        migrations.CreateModel(
            name='DepartmentHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=200, verbose_name='Отчество')),
                ('groups', models.ManyToManyField(to='info.group', verbose_name='Группы')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Управляющий',
            },
        ),
    ]
