# Generated by Django 4.1 on 2022-10-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_alter_departmenthead_options_curator'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='groups',
            field=models.ManyToManyField(blank=True, to='info.group', verbose_name='Группы'),
        ),
    ]
