# Generated by Django 4.1 on 2022-10-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_teacher_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['id_group'], 'verbose_name_plural': 'Группа'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name'], 'verbose_name_plural': 'Студент'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name'], 'verbose_name_plural': 'Предмет'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['last_name'], 'verbose_name_plural': 'Учитель'},
        ),
        migrations.AddField(
            model_name='group',
            name='semestr',
            field=models.CharField(blank=True, max_length=10, verbose_name='Семестр'),
        ),
        migrations.AddField(
            model_name='group',
            name='status',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
