# Generated by Django 4.1 on 2022-10-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_alter_group_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Период',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='departmenthead',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='departmenthead',
            name='user',
        ),
        migrations.DeleteModel(
            name='Curator',
        ),
        migrations.DeleteModel(
            name='DepartmentHead',
        ),
    ]
