# Generated by Django 4.1 on 2022-10-19 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_period_remove_departmenthead_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='info.period', verbose_name='Период'),
            preserve_default=False,
        ),
    ]
