# Generated by Django 4.1 on 2022-10-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_lesson_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Должность',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ['id'], 'verbose_name_plural': 'Период'},
        ),
    ]
