# Generated by Django 4.1 on 2022-10-19 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_post_alter_period_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='post',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='info.post', verbose_name='Должность'),
            preserve_default=False,
        ),
    ]
