# Generated by Django 4.1 on 2022-10-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_teacher_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_group', models.IntegerField()),
                ('weekday', models.IntegerField()),
                ('subject', models.TextField()),
                ('note', models.TextField()),
                ('semestr', models.IntegerField()),
                ('study_year', models.IntegerField()),
                ('subgroup', models.IntegerField()),
                ('type', models.IntegerField()),
                ('para', models.IntegerField()),
                ('time_start2', models.TextField()),
                ('time_start', models.TimeField()),
                ('time_end2', models.TextField()),
                ('time_end', models.TimeField()),
                ('parity', models.IntegerField()),
                ('lomka', models.IntegerField()),
                ('date_start', models.DateField()),
                ('date_start1', models.TextField()),
                ('date_end1', models.TextField()),
                ('date_lomka', models.TextField()),
                ('updates', models.DateTimeField()),
                ('delete', models.IntegerField()),
                ('txt', models.CharField(max_length=255)),
                ('el', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'lessons',
                'managed': False,
            },
        ),
    ]
