# Generated by Django 4.1 on 2022-11-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0013_lessonssti_lessonsteacherssti_delete_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='date_end',
            field=models.DateField(blank=True, default='2022-11-11', verbose_name='Дата Конца'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='period',
            name='date_start',
            field=models.DateField(blank=True, default='2022-11-11', verbose_name='Дата начала'),
            preserve_default=False,
        ),
    ]
