# Generated by Django 4.1 on 2022-11-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0014_period_date_end_period_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
