# Generated by Django 4.1 on 2022-11-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0016_lesson_id_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='info.subject', verbose_name='Предметы'),
        ),
    ]
