# Generated by Django 4.1 on 2022-11-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0017_teacher_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='term',
            field=models.CharField(default=1, max_length=2, verbose_name='Срок'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='period',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Период'),
        ),
    ]
