# Generated by Django 4.1 on 2022-11-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0018_period_term_alter_period_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='info.subject', verbose_name='Предметы'),
        ),
    ]
