# Generated by Django 4.1 on 2022-11-22 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0020_holyday'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stuff',
            new_name='Staf',
        ),
    ]
