# Generated by Django 4.1 on 2022-11-23 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0021_rename_stuff_staf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_and_Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.group', verbose_name='Номер группы')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name_plural': 'Предметы по группам',
                'unique_together': {('group', 'subject')},
            },
        ),
    ]
