# Generated by Django 4.1 on 2022-11-23 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0022_group_and_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_and_subject',
            name='period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='info.period', verbose_name='Период'),
            preserve_default=False,
        ),
    ]
