# Generated by Django 4.1 on 2022-11-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0023_group_and_subject_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='group_and_subjects',
            field=models.ManyToManyField(blank=True, to='info.group_and_subject', verbose_name='Предметы по группам'),
        ),
    ]
