# Generated by Django 4.1 on 2022-12-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0024_teacher_group_and_subjects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group_and_subject',
            options={'ordering': ['subject'], 'verbose_name_plural': 'Предметы по группам'},
        ),
        migrations.AlterField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='info.group_and_subject', verbose_name='Предметы'),
        ),
    ]
