# Generated by Django 4.1 on 2023-01-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0025_alter_group_and_subject_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Att_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('short_name', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Название',
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='group_and_subject',
            unique_together={('group', 'subject', 'period')},
        ),
    ]
