# Generated by Django 4.1 on 2023-01-20 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0026_att_status_alter_group_and_subject_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='status_new',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='info.att_status', verbose_name='Статус'),
        ),
    ]
