# Generated by Django 4.1 on 2023-01-20 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0027_attendance_status_new'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='att_status',
            options={'ordering': ['name'], 'verbose_name_plural': 'Статусы'},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='status_new',
        ),
        migrations.AlterField(
            model_name='att_status',
            name='short_name',
            field=models.CharField(max_length=200, verbose_name='Короткое название'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='info.att_status', verbose_name='Статус'),
        ),
    ]
