# Generated by Django 4.1 on 2023-01-20 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0028_alter_att_status_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='status_new',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='info.att_status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.IntegerField(default=1, max_length=1, verbose_name='Статус'),
        ),
    ]
