# Generated by Django 4.1 on 2023-01-20 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0029_attendance_status_new_alter_attendance_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='status_new',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='info.att_status', verbose_name='Статус'),
        ),
    ]
