# Generated by Django 4.1 on 2023-01-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0030_remove_attendance_status_new_alter_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='expelled',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
