# Generated by Django 4.1 on 2023-02-05 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0034_alter_lesson_id_group'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='group_and_subject',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='group_and_subject',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.group_contingent', verbose_name='Номер группы'),
        ),
        migrations.AlterUniqueTogether(
            name='group_and_subject',
            unique_together={('group', 'subject')},
        ),
        migrations.RemoveField(
            model_name='group_and_subject',
            name='period',
        ),
    ]
