# Generated by Django 4.1 on 2023-02-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0036_remove_teacher_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='groups',
            field=models.ManyToManyField(blank=True, to='info.group_contingent', verbose_name='Группы'),
        ),
    ]
