# Generated by Django 4.1 on 2023-02-05 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0037_teacher_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id_group',
        ),
    ]
