# Generated by Django 4.1 on 2023-02-05 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0039_student_id_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id_group',
        ),
    ]
