# Generated by Django 4.1 on 2023-02-13 08:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0041_student_id_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='time_create',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='time_update',
            field=models.DateField(auto_now=True, verbose_name='Время обновления'),
        ),
    ]
