# Generated by Django 4.1 on 2023-02-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0044_teacher_status_delete_historicaluser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='status',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
