# Generated by Django 4.1 on 2023-02-21 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0045_alter_teacher_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LessonsSTI',
        ),
        migrations.DeleteModel(
            name='LessonsTeachersSTI',
        ),
    ]
