# Generated by Django 4.1 on 2023-05-17 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0046_delete_lessonssti_delete_lessonsteacherssti'),
    ]

    operations = [
        migrations.CreateModel(
            name='School_Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=154, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Отчество')),
                ('phone_number', models.CharField(max_length=200, verbose_name='Номер телефона')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('vk_link', models.CharField(blank=True, max_length=200, verbose_name='Ссылка на страницу в социальной сети ВКонтакте')),
                ('fio_parent', models.CharField(max_length=200, verbose_name='ФИО Родителя')),
                ('phone_number_parent', models.CharField(max_length=200, verbose_name='Номер телефона')),
                ('school', models.CharField(max_length=200, verbose_name='Школа')),
                ('class_number', models.CharField(choices=[('1', '9 класс'), ('2', '10 класс'), ('3', '11 класс')], max_length=3, verbose_name='Класс')),
                ('format', models.CharField(choices=[('1', 'Онлайн'), ('2', 'Офлайн')], max_length=10, verbose_name='Формат')),
                ('time_create', models.DateField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateField(auto_now=True, verbose_name='Время обновления')),
                ('status', models.BooleanField(default=False, verbose_name='Активный')),
                ('subject', models.ManyToManyField(to='info.school_subjects', verbose_name='Предметы')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Школьник',
                'ordering': ['last_name'],
            },
        ),
    ]
