# Generated by Django 4.1 on 2023-05-19 12:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0047_school_subjects_school'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school_subjects',
            options={'verbose_name_plural': 'Предметы школьников'},
        ),
        migrations.AlterField(
            model_name='school',
            name='fio_parent',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='ФИО должно быть написано русскими буквами и начинаться с заглавной буквы', regex='[А-Я]{1}[а-я]+')], verbose_name='ФИО Родителя'),
        ),
        migrations.AlterField(
            model_name='school',
            name='first_name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Имя должно быть написано русскими буквами и начинаться с заглавной буквы', regex='[А-Я][а-я]+')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='school',
            name='last_name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Фамилия должна быть написана русскими буквами и начинаться с заглавной буквы', regex='[А-Я][а-я]+')], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='school',
            name='phone_number',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(code='invalid_phone_number_parent', message='Введите номер телефона в правильном формате', regex='^7\\d{10}$')], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='school',
            name='phone_number_parent',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(code='invalid_phone_number_parent', message='Введите номер телефона в правильном формате', regex='^7\\d{10}$')], verbose_name='Номер телефона Родителя'),
        ),
        migrations.AlterField(
            model_name='school',
            name='second_name',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.RegexValidator(message='Отчество должно быть написано русскими буквами и начинаться с заглавной буквы', regex='[А-Я][а-я]+')], verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='school',
            name='vk_link',
            field=models.CharField(blank=True, max_length=200, validators=[django.core.validators.URLValidator()], verbose_name='Ссылка на страницу в социальной сети ВКонтакте'),
        ),
        migrations.CreateModel(
            name='School_Subjects_dop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.CharField(choices=[('1', '9 класс'), ('2', '10 класс'), ('3', '11 класс')], max_length=3, verbose_name='Класс')),
                ('format', models.CharField(choices=[('1', 'Онлайн'), ('2', 'Офлайн')], max_length=10, verbose_name='Формат')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.school_subjects', verbose_name='Период')),
            ],
            options={
                'verbose_name_plural': 'Дополнительные предметы',
                'unique_together': {('subject', 'class_number', 'format')},
            },
        ),
        migrations.AddField(
            model_name='school',
            name='subject_dop',
            field=models.ManyToManyField(blank=True, to='info.school_subjects_dop', verbose_name='Дополнительные предметы'),
        ),
    ]
