# Generated by Django 4.1 on 2023-06-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0048_alter_school_subjects_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='user_pass',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Пароль'),
        ),
    ]
