# Generated by Django 4.1 on 2023-07-05 09:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0050_sish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='first_name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Имя должно быть написано русскими буквами и начинаться с заглавной буквы', regex='([А-Я][а-я])+')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='school',
            name='last_name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Фамилия должна быть написана русскими буквами и начинаться с заглавной буквы', regex='([А-Я][а-я])+')], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='school',
            name='second_name',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.RegexValidator(message='Отчество должно быть написано русскими буквами и начинаться с заглавной буквы', regex='([А-Я][а-я])+')], verbose_name='Отчество'),
        ),
    ]
