# Generated by Django 4.1 on 2023-09-07 21:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0051_alter_school_first_name_alter_school_last_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['-time_create'], 'verbose_name_plural': 'Школьник'},
        ),
        migrations.AddField(
            model_name='school',
            name='town',
            field=models.CharField(blank=True, max_length=200, validators=[django.core.validators.RegexValidator(message='Город должен быть написан русскими буквами и начинаться с заглавной буквы', regex='([А-Я][а-я])+')], verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='group',
            name='department',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='group',
            name='faculty',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='group',
            name='level',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='group',
            name='study_form',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Форма обучения'),
        ),
        migrations.AlterField(
            model_name='group_contingent',
            name='department',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='group_contingent',
            name='faculty',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='group_contingent',
            name='full_string',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='group_contingent',
            name='id_group_rasp',
            field=models.CharField(max_length=100, verbose_name='Номер группы расписание'),
        ),
        migrations.AlterField(
            model_name='group_contingent',
            name='level',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='group_contingent',
            name='study_form',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Форма обучения'),
        ),
        migrations.AlterField(
            model_name='school_subjects_dop',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.school_subjects', verbose_name='Предмет'),
        ),
    ]
